//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuonSach
    {
        public int MaPhieuMuon { get; set; }
        public Nullable<int> MaDG { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public Nullable<int> MaSach { get; set; }
    
        public virtual DOCGIA DOCGIA { get; set; }
        public virtual SACH SACH { get; set; }
    }
}
