//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuMuonSach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhieuMuonSach()
        {
            this.CT_PhieuMuonSach = new HashSet<CT_PhieuMuonSach>();
        }
    
        public int MaPhieuMuon { get; set; }
        public Nullable<int> MaDG { get; set; }
        public Nullable<System.DateTime> NgayMuon { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_PhieuMuonSach> CT_PhieuMuonSach { get; set; }
        public virtual DOCGIA DOCGIA { get; set; }
    }
}
